version: '2.2'
services:
  node:
    container_name: react
    image: node:alpine
    #cpuset: '0'
    #mem_limit: 64m
    stdin_open: true
    tty: true
    volumes:
      - $PWD/.npm:/root/.npm
      - $PWD/:/root/react
    working_dir: /root/react
    ports:
     - '80:80'
    networks:
      - net
networks:
  net:
